### ISSUE TITLE
Suggest to allow output to screen / stdout. 

### ISSUE THREAD

**Issue by DannyBen** [katzgrau/KLogger#34]
Setting the log dir to `/dev/tty` does not work, since you append the filename.
But changing it hardcoded in the file, to output to `/dev/tty` prints the log nicely to the screen.

Perhaps make a check for this condition and not try to append a filename and check for its `exists` status?

**Comment by jdunham22** [comment]
would like to help on this, @onnovos did you mod the code?

**Comment by onno-vos-dev** [comment]
(Continuing from my personal account)

@jdunham22 Yes I did and got it working when implementing customized log directory and logname as passables in the constructor. (See Pull Requests below) I haven't tried in an older version as @katzgrau already stated he wanted to implement that PR anyway. 

*nix:

```
[root@we-love-the-playground KloggerTest]# php KLoggerTest.php
[2015-03-02 16:26:37.696890] [INFO] Test output to Console!
```


Windows:

```
C:\php\php.exe -dxdebug.remote_enable=1 -dxdebug.remote_mode=req -dxdebug.remote_port=9000 -dxdebug.remote_host=127.0.0.1 C:\Projects\KLogger_PR\KLoggerTest.php
[2015-03-02 16:50:26.625200] [INFO] Test output to Console!
```

@katzgrau to avoid you having to merge a ton of Pull Requests, is it OK with you if I submit a single PR implementing:
All PR regarding custom naming of files can all be merged to one PR:
https://github.com/katzgrau/KLogger/pull/24 Log file naming
https://github.com/katzgrau/KLogger/pull/31 Add a third parameter to the constructor
https://github.com/katzgrau/KLogger/pull/32 Allows to customize log file name and extension; added rotation based on dates
https://github.com/katzgrau/KLogger/pull/33 Easy way of adding $logName possibility.  

If you'd like, I can have a go and try to merge the following at once as well:
https://github.com/katzgrau/KLogger/pull/8 Timer Methods  
 
Even though that will be a bit more tricky due to the older version of KLogger that is used in that PR.

**Comment by onno-vos-dev** [comment]
Now that I've been playing with this, I can see a use case for writing BOTH to file and stdout. Anyone objects with implementing this as an extra callable in the constructor? 

The below suggestion would allow to pass php://stdout as a $logDirectory if you only want to output to STDOUT while passing a $logName and TRUE would both output to file and STDOUT. Might be a neat implementation? :+1:  :-1:  ?

Which would result in something like:

```
public function __construct($logDirectory, $logName, $logToStdOut = false, $logLevelThreshold = LogLevel::DEBUG) {...}
```

**Comment by katzgrau** [comment]
Actually, I have a major change to support prefixes and file extensions. Because of the increased number of options, I'm just adding a third param (assoc array) to the constructor to take things that are basically just options.

Sit tight and I'll push those, hopefully today

**Comment by onno-vos-dev** [comment]
Cool, once pushed, I'll create a PR for this Issue if you don't take care of it already :) :+1:

**Comment by jdunham22** [comment]
I made my own changes to handle logging to php://* but I don't think it's anything special.  One separate idea is that if the private methods and properties became protected, it would be a lot easier to extend the functionality of the class.

**Comment by katzgrau** [comment]
Merged
