### ISSUE TITLE
class Logger extends AbstractLogger?

### ISSUE THREAD

**Issue by Jarzka** [katzgrau/KLogger#37]
Hi

It seems that Logger extends AbstractLogger which is not defined anywhere?

**Comment by katzgrau** [comment]
Hi! Since KLogger is now a composer package, it requires and implements the pph-fig logger interface AbstractLogger described here: https://github.com/php-fig/log

If you need a more stand-alone version, you might be able to use and older release of KLogger, which is available here (use the most recent 2012 release)
